### ISSUE TITLE
multi-thread support

### ISSUE THREAD

**Issue by tasinco** [subscan-explorer/scale.go#60]
Can you put put a mutex around `TypeRegistery`/`registerSiType` and make the library thread safe?

https://github.com/itering/scale.go/search?q=TypeRegistry&type=code
https://github.com/itering/scale.go/search?q=registeredSiType
more??

**Comment by freehere107** [comment]
@tasinco OK，thank you for the feedback, I will add it as soon

**Comment by ioannist** [comment]
> Can you put put a mutex around `TypeRegistery`/`registerSiType` and make the library thread safe?
> 
> https://github.com/itering/scale.go/search?q=TypeRegistry&type=code https://github.com/itering/scale.go/search?q=registeredSiType more??

Did you figure out how to make this thread-safe yourself? Any other variables we need to protect?
